DROP TABLE sys.COMPANY;
CREATE TABLE sys.COMPANY(
   ID        INT PRIMARY KEY NOT NULL,
   NAME      TEXT            NOT NULL,
   AGE       INT             NOT NULL,
   ADDRESS   CHAR(50),
   SALARY    REAL
);